// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data

const artisans = [
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    fname: 'Delba',
    lname: 'de Oliveira',
    email: 'delba@oliveira.com',
    password: '123456',
    category: 'Potter',
    story: 'In a small village nestled by the river, lived Delba, a talented potter. Her hands, calloused and skilled, molded clay into delicate bowls and vases that captured the essence of her surroundings. Each morning, she would gather clay from the riverbank, feeling the cool, pliable earth between her fingers. One day, she sculpted a vase so fine it seemed almost ethereal, inspired by the morning mist over the water. It quickly became the centerpiece of the village market, admired by all. Delba\'s creations were not just pottery; they were stories of the land, echoing its beauty and serenity.',
    image_url: '/sellers/delba-de-oliveira.png',
  },
  {
    id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    fname: 'Lee',
    lname: 'Robinson',
    email: 'lee@robinson.com',
    password: '123456',
    category: 'Blacksmith',
    story: 'In the heart of a bustling town, Lee\'s forge was always alive with the sounds of hammer striking anvil. A master blacksmith, he crafted tools and ornaments with unparalleled skill. One winter, a fierce storm hit the town, and many roofs were damaged. Lee worked tirelessly, forging nails and beams to help rebuild. His crowning achievement was a magnificent iron gate for the town\'s church, featuring intricate designs of leaves and vines. It stood as a testament to his dedication and craftsmanship, protecting the town with its strength and beauty.',
    image_url: '/sellers/lee-robinson.png',
  },
  {
    id: '3958dc9e-737f-4377-85e9-fec4b6a6442a',
    fname: 'Hector',
    lname: 'Simpson',
    email: 'hector@simpson.com',
    password: '123456',
    category: 'Glassblower',
    story: 'Hector\'s glassblowing studio was a place of magic and light. He transformed molten glass into delicate sculptures that seemed to capture the essence of fire and ice. One day, inspired by a snowflake he caught on his glove, Hector created a series of glass snowflakes, each unique and exquisite. When he displayed them in his shop, they caught the light and sparkled brilliantly, drawing admirers from afar. Hector\'s glassworks were not just decorations; they were frozen moments of beauty, capturing the fleeting wonders of nature.',
    image_url: '/sellers/hector-simpson.png',
  },
  {
    id: '3958dc9e-713f-4377-85e9-fec4b6a6442b',
    fname: 'Amy',
    lname: 'Burns',
    email: 'amy@burns.com',
    password: '123456',
    category: 'Weaver',
    story: 'Amy was known for her intricate weaving, creating textiles that told tales of her ancestors. In her cozy workshop, the loom\'s rhythmic clatter filled the air as she worked. One evening, while watching the sunset, she was inspired by the brilliant hues of the sky. She wove a tapestry that captured the sunset\'s essence, with threads of gold, crimson, and violet. When she unveiled it at the village fair, it left everyone in awe. Amy\'s tapestries were more than fabric; they were vibrant memories woven with love and tradition.',
    image_url: '/sellers/amy-burns.png',
  },
  {
    id: '3958dc9e-722f-4377-85e9-fec4b6a6442b',
    fname: 'Jared',
    lname: 'Palmer',
    email: 'jared@palmer.com',
    password: '123456',
    category: 'Carpenter',
    story: 'jared\'s woodworking shop was filled with the scent of fresh pine and the sounds of saws and chisels. Known for his meticulous attention to detail, he created furniture that was both functional and artistic. One spring, he crafted a rocking chair for the town\'s elderly storyteller, designing it with carvings of local legends. The chair became a cherished piece, offering comfort and stirring imaginations with its detailed carvings. Jared\'s work was more than carpentry; it was a blend of comfort and history, crafted with heart and soul.',
    image_url: '/sellers/jared-palmer.png',
  },
  {
    id: '3958dc9e-733f-4377-85e9-fec4b6a6442c',
    fname: 'Steph',
    lname: 'Dietz',
    email: 'steph@dietz.com',
    password: '123456',
    category: 'Jeweler',
    story: 'In a quaint, sunlit shop, Steph crafted jewelry that was renowned for its elegance and precision. She often used gems she found herself, scouring nearby hills and streams. One evening, she discovered a rare opal, its colors shifting like a sunset. She set it into a pendant, surrounded by delicate filigree. When she wore it to the town festival, its beauty captivated everyone. Steph\'s jewelry was not just adornment; it was a celebration of nature\'s hidden treasures, turned into timeless pieces of art.',
    image_url: '/sellers/steph-dietz.png',
  },
];

const products = [	
  {	
    id: '1958dc9e-712f-4377-85e9-fec4b6a6442a',	
    artisan_id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',	
    name: 'Human Face',	
    description: 'Creation Handcrafted Human Face Statue with Hand on His Mouth Decorative Showpiece Items for Home & Office, Art Figurines for Home Living Room Decorative Display.',	
    price: 3500,	
    category: 'Potter',	
    image_url: '/products/potter-fig.png',	
    type: 'Furniture',
    date: '2024-02-06',	
  },	
  {	
    id: '2958dc9e-742f-4377-85e9-fec4b6a6442a',	
    artisan_id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',	
    name: 'Door knocker',	
    description: 'Owl Door Knockers for Front Door, Small Mini Gate Knockers with Black Finish, Vintage Rustic Door Knobs/Handle for Barn Door Farmhouse Wall.',	
    price: 3500,	
    category: 'Blacksmith',	
    image_url: '/products/blacksmith-door-acc.png',	
    type: 'Furniture',
    date: '2024-02-06',	
  },	
  {	
    id: '4258dc9e-712f-4377-85e9-fec4b6a6442a',	
    artisan_id: '3958dc9e-713f-4377-85e9-fec4b6a6442b',	
    name: 'Yarn paintings',	
    description: 'The "nierikas" are important ritual and spiritual art objects in the Huichol culture. They are also known as "tablas de estambre" in Spanish..',	
    price: 4500,	
    category: 'Weaver',	
    image_url: '/products/ahc-00120-300x300.jpg',	
    type: 'Furniture',
    date: '2024-01-10',
  },	
  {	
    id: '4158dc9e-712f-4377-85e9-fec4b6a6442b',	
    artisan_id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',	
    name: 'Ring Standing Shelf',	
    description: 'Showcase cherished pieces and make a dynamic display with this modern metal shelf. 27.5x7x31H" Black powder-coated metal No assembly required Wipe clean.',	
    price: 520000,	
    category: 'Blacksmith',	
    image_url: '/products/blacksmith-house-acc.png',	
    type: 'Furniture',
    date: '2024-01-10',	
  },	
  {	
    id: '4558dc9e-712f-4377-85e9-fec4b6a6442c',	
    artisan_id: '3958dc9e-713f-4377-85e9-fec4b6a6442b',	
    name:'Huichol Art Backpack',	
    description: 'Huichol art yarn backpacks are traditional handcrafted pieces of the Huichol culture, an indigenous ethnic group that inhabits the mountainous region of the Sierra Madre Occidental in Mexico.',	
    price: 70000,	
    category: 'Weaver',	
    image_url: '/products/ahar-00713-300x300.jpg',	
    type: 'Personal stuff',
    date: '2024-01-18',
  },	
  {	
    id: '7158dc9e-712f-4377-85e9-fec4b6a6442f',	
    artisan_id: '3958dc9e-733f-4377-85e9-fec4b6a6442c',	
    name: 'bracelet',	
    description: 'These bracelets stand out for their vibrant colors and intricate designs, often representing traditional symbols, elements of nature or spiritual motifs significant to the Huichol culture.',	
    price: 30000,	
    category: 'Jeweler',	
    image_url: '/products/jewelry-bracelet.png',	
    type: 'Personal stuff',
    date: '2024-02-06',
  },	
  {	
    id: '3858dc9e-712f-4117-85e9-fec4b6a6442a',	
    artisan_id: '3958dc9e-722f-4377-85e9-fec4b6a6442b',	
    name: 'Wood Egg Tray',	
    description: 'Mini Bamboo wood Egg Tray Set (6 Holes), one small Racks, Premium Rustic Wooden Egg Holder For Deviled Egg, Usable in Kitchen Refrigerator, or Countertop for Display or Storage.',	
    price: 25000,	
    category: 'Carpenter',	
    image_url: '/products/wood-kitchen-acc.png',	
    type: 'Furniture',
    date: '2024-02-18',
  },  
  {	
    id: '5858dc9e-712f-4377-85e9-fec4b6a6442e',	
    artisan_id: '3958dc9e-733f-4377-85e9-fec4b6a6442c',	
    name: 'Microchaquira earrings',	
    description: 'Huichol art microchaquira earrings; handmade artisan jewelry pieces that reflect the rich tradition and artistic skill of the Huichol culture.',	
    price: 25000,	
    category: 'Jeweler',	
    image_url: '/products/jewelry-earrings.png',	
    type: 'Personal stuff',
    date: '2024-01-18',
  },
  {	
    id: '4158dc9c-712f-4377-87e9-fec4b6a6442a',	
    artisan_id: '3958dc9e-737f-4377-85e9-fec4b6a6442a',	
    name: 'Footed Aqua Spiral Bowl',	
    description: 'This hand-blown glass bowl was created by first rolling a molten clear bubble of glass through a layer of sparkly aqua glass chunks that are about the size of rock salt and then rolling it though similar sized white powdered glass.',	
    price: 30000,	
    category: 'Glassblower',	
    image_url: '/products/glassblower-bowl.png',	
    type: 'Furniture',
    date: '2024-01-10',
  },	
  {	
    id: '1958dc9e-712f-4377-88e9-fec4b6a6442b',	
    artisan_id: '3958dc9e-722f-4377-85e9-fec4b6a6442b',	
    name: 'Wooden basket',	
    description: 'This is for a custom handmade wooden basket.  Perfect for gardening, useful storage, thoughtful gift and to use as a beautiful home decor accent.   You can stain or paint this basket to your desired color and even add stenciling to the sides.',	
    price: 3500,	
    category: 'Carpenter',	
    image_url: '/products/wood-tool-acc.png',	
    type: 'Furniture',
    date: '2024-01-21',	
  },
  {	
    id: '4158dc9b-712f-4377-67e9-fec4b6a6442b',	
    artisan_id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',	
    name: 'Large potter vase',	
    description: 'Distressed potter vase, home decoration, out door decoration, artificial flower vase, home decoration, festival decoration, holiday arrangement, office desk decoration, desk decoration, room decoration.',	
    price: 30000,	
    category: 'Potter',	
    image_url: '/products/glassblower-fig.png',	
    type: 'Furniture',
    date: '2024-01-10',
  },	
  {	
    id: '2158dc9b-712f-4347-67e9-fec4b6a6442a',	
    artisan_id: '3958dc9e-737f-4377-85e9-fec4b6a6442a',	
    name: 'Sparkle Crystal Swan',	
    description: 'The crystal swan is packaged in a elegant gift box,it is a perfect gift for swan lovers, crystal fans,crystal collectors ,wedding and the holiday party.',	
    price: 30000,	
    category: 'Glassblower',	
    image_url: '/products/glassblower-fig.png',	
    type: 'Furniture',
    date: '2024-01-06',
  },	  
];	

const reviews = [	
  {	
    id: '2958dc9e-312f-4377-85e9-fec4b6a6442a',	
    product_id: '1958dc9e-712f-4377-85e9-fec4b6a6442a',	
    user_name: 'Harry Vazquez',	
    comment: 'Sublime product',	
    rating: 4,	
  },	
  {	
    id: '3958dc9e-752f-4477-85e9-fec4b6a6442a',	
    product_id: '2958dc9e-742f-4377-85e9-fec4b6a6442a',	
    user_name: 'Louis Lane',	
    comment: 'magnificent product',	
    rating: 3,	
  },	
  {	
    id: '4358dc9e-612f-4167-85e9-fec4b6a6442a',	
    product_id: '4258dc9e-712f-4377-85e9-fec4b6a6442a',	
    user_name: 'Jerry McGuire',	
    comment: 'spectacular product',	
    rating: 4,	
  },	
  {	
    id: '4358dc9e-321f-4357-85e9-fec4b6a6442b',	
    product_id: '4158dc9e-712f-4377-85e9-fec4b6a6442b',	
    user_name: 'Forrest Larson',		
    comment: 'Excellent product',	
    rating: 4,	
  },	
  {	
    id: '4558dc9e-402f-4317-85e9-fec4b6a6442c',	
    product_id: '4558dc9e-712f-4377-85e9-fec4b6a6442c',	
    user_name: 'David Brenton',	
    comment: 'Nice product',	
    rating: 4,	
  },	
  {	
    id: '4158dc9e-121f-4387-85e9-fec4b6a6442a',	
    product_id: '7158dc9e-712f-4377-85e9-fec4b6a6442f',	
    user_name: 'Katy Adams',	
    comment: 'Wonderful product',	
    rating: 4,	
  },	
  {	
    id: '3858dc9e-813f-4377-85e9-fec4b6a6442b',	
    product_id: '5858dc9e-712f-4377-85e9-fec4b6a6442e',	
    user_name: 'Lesly Tompson',	
    comment: 'Lovely product',	
    rating: 4,	
  },	
];

module.exports = {
  artisans,
  products,
  reviews,
};
